#!/bin/bash
# This code is awful but it works

DEFAULT_THEME="$HOME/.config/rofi/config.rasi"
THEME="$1"
THEME2="$2"

# setting up symbols used in the menu. you`re encouraged to change them
play="󰐊"
pause="󰏤"
play_pause="󰐎"
stop_="󰓛"
next="󰒭"
prev="󰒮"
loop="󰑖"
shuffle="󰒝"
back="󰁝"

active="󰝚"
inactive="󰝛"

# setting up options shown in the second level menu. again, you are encouraged to change them
# can include $back $play $pause $play-pause $_stop $next $prev $loop $shuffle in any order
options="$stop_\n$prev\n$play_pause\n$next\n$loop"

label_all_active="Active"
label_all_inactive="Inactive"

# first menu level loop
while true; do
    players="$label_all_active"$'\n'"$label_all_inactive"
    # there is no way to target all players at once with mpris-ctl
    # so we get active and inactive players separately
    active_players="$(mpris-ctl --player active list)"
    inactive_players="$(mpris-ctl --player inactive list)"
    if [[ -n $active_players ]]; then
        players="$players"$'\n'"$active_players"
    fi
    if [[ -n $inactive_players ]]; then
        players="$players"$'\n'"$inactive_players"
    fi
    readarray -t players <<<"$players"
    if [[ ${#players[@]} -le 2 ]]; then
        # if $players only has 'active' and 'inactive' there's nothing running
        rofi -e "No MPRIS players running."
        exit 0
    fi
    player_list_display="$label_all_active"$'\n'"$label_all_inactive"
    for player in "${players[@]:2}"; do
        # begin loop at index 2 to skip 'Active' and 'Inactive'
        if [[ "$(mpris-ctl --player "$player" status)" == "Playing" ]]; then
            status="$active"
        else
            status="$inactive"
        fi
        player_list_display+="\n$status $(mpris-ctl --player "$player" info "%player_name\t%artist_name - %track_name")"
    done
    rofi_par1=(
        -dmenu
        -p ""
        -format i
        -theme "${THEME:-$DEFAULT_THEME}"
    )

    player_index="$(echo -e "$player_list_display" | rofi "${rofi_par1[@]}")"
    if [[ -z $player_index ]]; then
        # $player_index is empty if rofi gets passed ESC
        break
    fi
    chosen_player="${players[$player_index]}"
    rofi_par2=(
        -no-fixed-num-lines
        -selected-row 2
        -dmenu
        -p "$chosen_player"
        -theme "${THEME2:-${THEME:-$DEFAULT_THEME}}"
    )
    if [[ "$chosen_player" == "$label_all_active" ]]; then chosen_player="active"; fi
    if [[ "$chosen_player" == "$label_all_inactive" ]]; then chosen_player="inactive"; fi
    # second menu level loop
    while true; do
        chosen_option="$(echo -e "$options" | rofi "${rofi_par2[@]}")" 
        case $chosen_option in
            "$back")
                break
                ;;
            "")
                # ESC handling
                break
                ;;
            "$play")
                player_option="play"
                ;;
            "$pause")
                player_option="pause"
                ;;
            "$play_pause")
                player_option="pp"
                ;;
            "$stop_")
                player_option="stop"
                ;;
            "$next")
                player_option="next"
                ;;
            "$prev")
                player_option="prev"
                ;;
            "$loop")
                player_option="repeat --track"
                ;;
            "$shuffle")
                player_option="shuffle"
                ;;
        esac
        mpris-ctl --player "$chosen_player" "$player_option"
    done
done
